variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  CI_IMAGE_NAME: "harbor.miracum.org/dqa_base_image/base_image:development"
  R_PKG_NAME: "miRacumDQA"
  DOCKER_REGISTRY: "harbor.miracum.org"

# Example gitlab-ci for testing R packages: 
# https://gist.github.com/artemklevtsov/785ed0472c167246e947a75216852e10


stages:
  - get_base_image
  - build
  - deploy


.docker_registry:
  before_script:
    - echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} ${DOCKER_REGISTRY} --password-stdin
    - git clone https://oauth2:${CI_JOB_TOKEN}@gitlab.miracum.org/miracum/dqa/dqatool_deployment.git dqa_base_image
    - cd dqa_base_image
  after_script:
    - docker logout ${DOCKER_REGISTRY}


build_new_base_image:
  stage: get_base_image
  image: docker:git
  extends: .docker_registry
  script:
    - sh deploy_base_image.sh -t development
  only:
   refs:
     - master
     - tags

check:
  stage: build
  image: ${CI_IMAGE_NAME}
  # extends: .docker_registry
  allow_failure: true # necessary when having development-packages (in remotes-section of DESCRIPTION)
  script:
    - R -e "rcmdcheck::rcmdcheck(path = '.', args = c('--no-tests', '--no-vignettes', '--as-cran'), build_args = c('--no-build-vignettes'), check_dir = '${CI_PROJECT_DIR}/ci')"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.Rcheck"
    when: on_failure # upload check artifacts when job fails!
    expire_in: 1 week

create_manual:
  image: ${CI_IMAGE_NAME}
  # extends: .docker_registry
  stage: build
  allow_failure: true
  script:
    - R -e "devtools::build_manual(pkg = '.', path = '${CI_PROJECT_DIR}/ci')"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.pdf"
    expire_in: 1 week
  only:
    refs:
      - master
      - tags

build_source_and_binary:
  image: ${CI_IMAGE_NAME}
  # extends: .docker_registry
  stage: build
  script:
    - R -e "devtools::build(pkg = '.', path = '${CI_PROJECT_DIR}/ci', binary = FALSE, vignettes = FALSE)"
    - R -e "devtools::build(pkg = '.', path = '${CI_PROJECT_DIR}/ci', binary = TRUE, vignettes = FALSE)"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/ci/*.tar.gz"
    expire_in: 1 week
  only:
    refs:
      - master
      - tags

# To have the coverage percentage appear as a gitlab badge follow these
# instructions:
# https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing
# The coverage parsing string is
# Coverage: \d+\.\d+


testing:
  image: ${CI_IMAGE_NAME}
  # extends: .docker_registry
  stage: build
  script:
    - R -e "devtools::test(pkg = '.')"


# To produce a code coverage report as a GitLab page see
# https://about.gitlab.com/2016/11/03/publish-code-coverage-report-with-gitlab-pages/

install:
  image: ${CI_IMAGE_NAME}
  # extends: .docker_registry
  stage: deploy
  script:
    - R -e "devtools::install(pkg = '.', upgrade = 'always')"



build_release_image:
  stage: deploy
  image: docker:git
  when: on_success
  before_script:
    - apt-get update && apt-get install git -y --no-install-recommends
  script:
    - mkdir ci_tmp
    - cd ci_tmp
    - git clone https://gitlab.miracum.org/miracum/dqa/miRacumDQA.git
    - cd miRacumDQA
    - miRacumDQA_tag=$(git describe --tags `git rev-list --tags --max-count=1`) # gets tags across all branches, not just the current branch
    - miRacumDQA_tag_no_prefix=$(echo ${miRacumDQA_tag} | sed "s/v//") # Replaces every 'v' in the tag with a blank ''.
    - echo "DIZutils_tag ${DIZutils_tag}"
    - echo "DQAstats_tag ${DQAstats_tag}"
    - echo "DQAgui_tag ${DQAgui_tag}"
    - echo "miRacumDQA_tag ${miRacumDQA_tag}"
    - echo "miRacumDQA_tag_no_prefix ${miRacumDQA_tag_no_prefix}"
    - cd ../
    - git clone https://oauth2:${CI_JOB_TOKEN}@gitlab.miracum.org/miracum/dqa/dqatool_deployment.git dqatool_deployment
    - cd dqatool_deployment
    - sed -i -e 's/IMAGE_TAG=[0-9]\.[0-9]\.[0-9]/IMAGE_TAG='"${miRacumDQA_tag_no_prefix}"'/' deploy/.env
    - git add deploy/.env
    - git config --global user.email "releasebot@gitlab.miracum.org"
    - git config --global user.name "Release Bot"
    - git commit -m "[Autocommit from miRacumDQA] Version updated to ${miRacumDQA_tag_no_prefix}"
    - git push origin master
    - git tag -a ${miRacumDQA_tag} -m "Release ${miRacumDQA_tag}"
    - git push origin ${miRacumDQA_tag}
    - cd ../../
    - rm -rf ci_tmp
  only:
    refs:
      - tags
