version: '3'

services:
  dqatool:
    container_name: dqa-miracum
    image: docker.miracum.org/dqa/miracumdqa:2.0.3
    restart: unless-stopped
    volumes:
      - /home/i2b2/start/Input:/home/input
    ports:
      - "3838:3838"
    environment:
      - I2B2_PASSWORD=i2b2
      - OMOP_PASSWORD=admin1
    networks:
      - miracum-net

networks:
    miracum-net:
       external: true
