version: '3'

services:
  dqatool:
    container_name: dqa-miracum
    image: docker.miracum.org/dqa/miracumdqa:2.0.0
    restart: unless-stopped
    volumes:
      - ./etl/input_files/p21_i2b2/merged:/home/input
    ports:
    - "3838:3838"
    networks:
    - miracum-net

networks:
    miracum-net:
       external: true
