version: '3'

services:
  dqatool:
    container_name: dqa-miracum
    image: dqa-miracum
    restart: unless-stopped
    volumes:
      - /home/i2b2/start:/home/i2b2/start
    ports:
    - "3838:3838"
    networks:
    - i2b2_i2b2net

networks:
    i2b2_i2b2net:
       external: true

# debugging cmd:
# sudo docker run -it --rm -p 3838:3838 -v /home/i2b2/start:/home/i2b2/start --network="i2b2_i2b2net" dqa-miracum bash

# https://superuser.com/questions/948381/how-to-get-stdout-of-a-lost-session
# trace stdout of rsession
# first, get pid of r-process
# sudo docker exec -it dqa-miracum bash -c "top"
# sudo docker exec -it dqa-miracum bash -c "strace -p {R-ID} -e write=1,2"
