version: '3'

services:
  dqatool:
    container_name: dqa-miracum
    image: dqa-miracum
    restart: unless-stopped
    ports:
    - "3838:3838"
    networks:
    - i2b2net

networks:
    i2b2net:
       driver: bridge

