version: '3'

services:
  dqatool:
    container_name: dqa-miracum
    image: docker.miracum.org/dqa/miracumdqa:latest
    restart: unless-stopped
    volumes:
      - /home/i2b2/start/Input:/home/input
    ports:
    - "3838:3838"
    # - "3839:3839" # debugging port
    networks:
    - miracum-net

networks:
    miracum-net:
       external: true

# debugging cmd:
# sudo docker run -it --rm -p 3838:3838 -v /home/i2b2/start:/home/i2b2/start --network="i2b2_i2b2net" dqa-miracum bash

# sudo docker logs -f dqa-miracum

# $ R
# > library(miRacumDQA)
# > options(shiny.host = "0.0.0.0")
# > launchDQAtool(3839)
